# Generated by Django 4.2.6 on 2023-10-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'admin'), (1, 'client'), (2, 'Employee_Fraud'), (3, 'Employee_full'), (4, 'Employee_Support'), (5, 'Acountant'), (6, 'Professor')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
    ]
