# Generated by Django 4.2.6 on 2023-10-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'admin'), (1, 'client'), (2, 'Employee_Fraud'), (3, 'Employee_full'), (4, 'Employee_Support'), (5, 'Acountant'), (6, 'Professor')], null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('totaltransaction', models.IntegerField(null=True)),
                ('Businessphonenumber', models.IntegerField(null=True)),
                ('Businessemail', models.EmailField(max_length=100, null=True, unique=True)),
                ('totalammount', models.IntegerField(blank=True, null=True)),
                ('disputes', models.IntegerField(blank=True, null=True)),
                ('totaldisputesammount', models.IntegerField(blank=True, null=True)),
                ('accceptedtrans', models.IntegerField(blank=True, null=True)),
                ('charbackcountrate', models.IntegerField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('declinetrans', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile')),
                ('city', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bin', models.CharField(max_length=100)),
                ('Lastfour', models.CharField(max_length=100)),
                ('ammount', models.IntegerField()),
                ('payout', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('InternalTransactionid', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
