# Generated by Django 4.2.6 on 2023-10-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Acountant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Employee_Fraud',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Employee_Support',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Employee_full',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Professor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'admin'), (1, 'client'), (2, 'Employee_Fraud'), (3, 'Employee_full'), (4, 'Employee_Support'), (5, 'Acountant'), (6, 'Professor')], null=True),
        ),
    ]
